# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
print(np.show_config)

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
a=np.zeros(10)

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
print((a.size*a.itemsize),"bytes")

80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
print(np.info(np.add))

None


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
b=np.zeros(10)
b[4]=1
print(b)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
c=np.arange(10,50)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
c=np.arange(10,50)
print(c[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
d=np.arange(0,9).reshape(3,3)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
e=[1,2,0,0,4,0]
print(np.nonzero(e))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
np.eye(3).reshape(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
np.random.random((3,3,3))

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
e=np.random.random((10,10))
print(e.min(),e.max())


0.009868909155154593 0.992702468174733


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
f=np.arange(31)
print(f.mean())

15.0


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
g=np.ones((9,9))
g[1:8,1:8]=0
g

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
x=np.arange(2,14).reshape(4,3)
x=np.pad(x,pad_width=1,mode="constant",constant_values=0)
x

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
h=[1,2,3,4]
print(h)
np.diag(h,k=-1)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
v=np.zeros((8,8),dtype=int)
v[1::2,::2]=1
v[::2,1::2]=1
print(v)
     



#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
i=np.random.randint((6,7,8))
np.unravel_index(i, 100)

(array([3, 1, 1]),)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
np.tile([1], (8,8))

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x=np.random.random((5,5))
max,min=x.max(),x.min()
x=(x-min)/(max-min)
x

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("r", np.ubyte, 1),("g", np.ubyte, 1),("b", np.ubyte, 1),("a", np.ubyte, 1)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
a=np.ones((5,3))
b=np.ones((3,2))
np.dot(a,b)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [46]:
h=np.arange(11)
h[(3<h) & (h<=8)]*= -1
print(h)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
All are legal


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
error

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
c=np.array([1.5,2.3,4.2])
np.ceil(c)

array([2., 3., 5.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
v=np.array([1.5,2.3,4.2])
g=np.array([5,2.3,4.2,58])
np.intersect1d(v,g)

array([2.3, 4.2])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
no, False

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [49]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
c=np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(c)

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A=np.array([1,2,3,4])
B=np.array([1,2,3,4])
print(np.multiply((np.add(A,B)),(np.divide(np.negative(A),2))))

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [50]:
a=np.random.uniform(0,10,10)

print (a-a%1)
print (np.floor(a))
print (np.ceil(a)-1)
print (a.astype(int))
print (np.trunc(a))

[9. 3. 3. 6. 0. 1. 4. 4. 7. 3.]
[9. 3. 3. 6. 0. 1. 4. 4. 7. 3.]
[9. 3. 3. 6. 0. 1. 4. 4. 7. 3.]
[9 3 3 6 0 1 4 4 7 3]
[9. 3. 3. 6. 0. 1. 4. 4. 7. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
d=np.array([[0,1,2,3,4],[0,1,2,3,4],[0,1,2,3,4],[0,1,2,3,4],[0,1,2,3,4]])
d

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
v=[i/2 for i in range(5)]
np.fromiter(v,int)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
np.linspace(0.1,0.9,10)

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
x=np.random.random(10)
np.sort(x)

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
n=np.linspace(0.1,0.9,10)
np.add.reduce(n)

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A=np.array([1,2,3,4])
B=np.array([1,2,3,4])
np.allclose(A,B)

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:

A=np.array([1,2,3,4])
b=A.flags.writeable=False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
z= np.random.random((10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.16113019 0.17622323 1.14857404 0.13568247 0.15754784 0.79602704
 0.62800271 0.89597485 0.52109913 0.67381534]
[0.81491519 0.53602178 0.92395688 0.06212204 1.06136806 1.25414971
 0.74379977 0.16641302 1.20548272 0.04158965]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
b=np.random.rand(10)
m=np.argmax(b)
b[m]=0
b

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
x = np.linspace(0, 1, 3)
y = np.linspace(0, 1, 3)
xv, yv = np.meshgrid(x, y)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
x = np.linspace(0, 1, 3)
y = np.linspace(0, 1, 3)
c= 1.0 / (x.reshape((-1,1)) - y)
c

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
ii32 = np.iinfo(np.int32)
ii32.min,ii32.max


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
x=np.arange(10000)
np.set_printoptions(threshold=np.inf)
x

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
x=12.56
np.argmin(x)

0

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
h=np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),('color',    [ ('r', float, 1),('g', float, 1), ('b', float, 1)])])
print(h)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
b=np.random.random((10,2))
x,y = np.atleast_2d(b[:,0], b[:,1])
g=np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(g)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
array1 = np.array([[11.21, 19.21], [46.21, 18.21], [29.21, 21.21]])
int_array =array1.astype(int)
print(int_array)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s=StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
h=np.genfromtxt(s,delimiter=",",dtype=np.int)
print(h)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
a = np.array([[1, 2], [3, 4]])
for index, x in np.ndenumerate(a):
    print(index, x)

#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
c = np.sqrt(x*x+y*y)
s, n = 1.0, 0.0
g = np.exp(-( (c-n)**2 / ( 2.0 * s**2 ) ) )
g


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
v=np.arange(8)
np.put(v,[0],[56])
v

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
import numpy as np
z=np.random.random((2,2))
print(z)
b=np.mean(z,axis=1,keepdims=True)
print(b)
print(z-b)


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
v=np.random.randint(100,size=(5,4))
print(v)
v[:,0].argsort()

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
a=[[1,8,2],[5,2,4]]
np.any(a=0)

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
u=np.random.uniform(0,1,10)
j=0.5
m=u.flat[np.abs(u-u).argmin()]
print(m)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
a=np.arange(3).reshape(3,1)
b=np.arange(3).reshape(1,3)
it=np.nditer([a,b,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class attribute:
  def config (self):
    a=[1,2,3]
    print(a)
com1=attribute()
com1.config()

[1, 2, 3]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
a=np.ones(10)
i=np.random.randint(0,len(Z),20)
np.add.at(a,i,1)
print(a)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
a = [1,2,3,4]
b = [5,6,7,8]
c = np.bincount(a,b)
c

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
x=np.random.randint(0,10,(3,4,3,4))
sum = x.sum(axis=(-2,-1))
print(sum)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
p=np.random.uniform(0,1,100)
j=np.random.randint(0,10,100)
t=np.bincount(j,weights=p)
g=np.bincount(j)
print(t/g)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
a=np.random.uniform(0,1,(5,5))
b=np.random.uniform(0,1,(5,5))
np.diag(np.dot(a, b))

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
g=np.array([1,2,3,4,5])
n=3
f=np.zeros(len(g) + (len(g)-1)*(n))
f[::n+1]=g
print(f)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
x=np.ones((5,5,3))
y=2*np.ones((5,5))
print(x* y[:,:,None])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
f=np.arange(16).reshape(4,4)
f[[0,1]] = f[[1,0]]
print(f)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
x=np.random.randint(0,100,(10,3))
t=np.roll(x.repeat(2,axis=1),-1,axis=1)
t=t.reshape(len(t)*3,2)
t=np.sort(t,axis=1)
r=t.view( dtype=[('p0',t.dtype),('p1',t.dtype)])
r=np.unique(r)
print(r)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
y=np.bincount([1,1,2,3,4,4,6])
t= np.repeat(np.arange(len(y)),y)
print(t)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a,n=3) :
    ret = np.cumsum(a,dtype=float)
    ret[n:] = ret[n:]-ret[:-n]
    return ret[n - 1:]/n
k=np.arange(20)
print(moving_average(k,n=3))

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks
def daas(a,b):
    shape = (a.size-b +1,b)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
p=daas(np.arange(10),3)
print(p)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
h=np.random.randint(0,10,100)
np.logical_not(h, out=h)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T=P1 - P0
    L=(T**2).sum(axis=1)
    U=-((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U=U.reshape(len(U),1)
    D=P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0=np.random.uniform(-10,10,(10,2))
P1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0=np.random.uniform(-10, 10, (10,2))
P1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
s=np.arange(1,15,dtype=np.uint32)
g=np.lib.stride_tricks.as_strided(s,(11,4),(4,4))
print(g)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
a=np.random.uniform(0,5,(10,10))
d,g,t = np.linalg.svd(a) 
r = np.sum(g > 1e-10)
print(r)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
a=np.random.randint(0,60,50)
print(np.bincount(a).argmax())

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
a=np.random.randint(0,5,(10,10))
n=3
i=1+(a.shape[0]-3)
j=1+(a.shape[1]-3)
c=np.lib.stride_tricks.as_strided(a, shape=(i, j, n, n), strides=a.strides + a.strides)
print(c)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [41]:
class rass(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(rass, self).__setitem__((i,j), value)
        super(rass, self).__setitem__((j,i), value)
def function1(p):
    return np.asarray(p + p.T - np.diag(p.diagonal())).view(rass)
l=function1(np.random.randint(0,24,(6,6)))
l[5,3]=56
print(l)

[[18 18 20 25 28 18]
 [18 10 13 21 29 22]
 [20 13  3 25 23 31]
 [25 21 25 12 15 56]
 [28 29 23 15  3  4]
 [18 22 31 56  4  0]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p,n=10,20
u=np.ones((p,n,n))
i=np.ones((p,n,1))
k=np.tensordot(u,i,axes=[[0, 2],[0, 1]])
print(k)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
g=np.ones((16,16))
k=4
b=np.add.reduceat(np.add.reduceat(g, np.arange(0, g.shape[0], k), axis=0), np.arange(0, g.shape[1], k), axis=1)
print(b)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
k=np.arange(50000)
np.random.shuffle(k)
n=4
print(k[np.argsort(k)[-n:]])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(array):
    array=[np.asarray(a) for a in array]
    shape=(len(x) for x in array)
    ix=np.indices(shape,dtype=int)
    ix=ix.reshape(len(array),-1).T
    for n,arr in enumerate(array):
        ix[:,n] = array[n][ix[:, n]]
    return ix
print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
x=np.array([("Hello", 8.9, 5),("India", 5.2, 4)])
p=np.core.records.fromarrays(x.T, names='1, 2, 3',formats = 'S8, f8, i8')
print(p)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [42]:
x=np.random.randint(5e7)
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

The slowest run took 19.10 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.28 µs per loop
The slowest run took 10.00 times longer than the fastest. This could mean that an intermediate result is being cached.
10000000 loops, best of 5: 140 ns per loop


ValueError: ignored

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
a=np.random.randint(0,5,(8,3))
vars=np.random.randint(0,5,(2,2))
j=(a[..., np.newaxis, np.newaxis]==v)
w=np.where(j.any((3,1)).all(1))[0]
print(w)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
f=np.random.randint(0,5,(10,3))
print(f)
t=np.all(f[:,1:] == f[:,:-1], axis=1)
h= f[~t]
print(h)
h=f[f.max(axis=1) != f.min(axis=1),:]
print(h)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
d=np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(d[:, np.newaxis], axis=1))

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
Z=np.random.randint(0,2,(6,3))
T=np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
b= Z[idx]
print(b)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
a=np.random.uniform(0,1,10)
b=np.random.uniform(0,1,10)
np.einsum('i->', a)       
np.einsum('i,i->i', a, b) 
np.einsum('i,i', a, b)    
np.einsum('i,j->ij', a, b)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [14]:
phi=np.arange(0,10*np.pi,0.1)
a=1
x=a*phi*np.cos(phi)
y=a*phi*np.sin(phi)
dr=(np.diff(x)**2 + np.diff(y)**2)**.5
r=np.zeros_like(x)
r[1:]=np.cumsum(dr)                
r_int=np.linspace(0,r.max(),200) 
x_int=np.interp(r_int,r,x)       
y_int=np.interp(r_int,r,y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
f=np.random.randint((4,3))
v=4
h=np.logical_and.reduce(np.mod(f, 1) == 0, axis=-1)
h&= (f.sum(axis=-1) == v)
print(f[h])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:

x = np.random.randn(100) 
n = 1000 
i = np.random.randint(0, x.size, (n, x.size))
b = x[i].mean(axis=1)
v= np.percentile(b, [2.5, 97.5])
print(v)